[package]
name = "tinyspec"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/nmcdaines/tinyspec"
description = "A tiny framework for writing specs for use in language models."
license = "MIT"

[dependencies]
